import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class PdtStructureService {
  getPdtStructureData() {
    return [
      {
        portfolioId: 101,
        portfolioName: 'Digital Transformation & Innovation Portfolio',
        portfolioTechMgr: 'Sarah Johnson',
        pdtCount: 1,
        teamCount: 10,
        productCount: 5,
        pdt: {
          pdtId: 201,
          pdtName: 'Customer Experience PDT',
          pdtTechMgr: 'David Rodriguez',
          teamCount: 10,
          productCount: 5,
          products: [
            {
              productId: 1,
              productName: 'Learning',
              productOwner: 'Alice Johnson',
              productType: 'Platform',
              status: 'Active',
            },
            {
              productId: 2,
              productName: 'Job Platform Legacy',
              productOwner: 'Bob Smith',
              productType: 'Legacy System',
              status: 'Maintenance',
            },
            {
              productId: 3,
              productName: 'Risk',
              productOwner: 'Carol Davis',
              productType: 'Compliance',
              status: 'Active',
            },
            {
              productId: 4,
              productName: 'Insights',
              productOwner: 'David Wilson',
              productType: 'Analytics',
              status: 'Active',
            },
            {
              productId: 5,
              productName: 'Hiring',
              productOwner: 'Eva Martinez',
              productType: 'Core Business',
              status: 'Active',
            },
          ],
          teams: [
            {
              teamId: 301,
              teamName: 'Mobile Apps Team',
              type: 'Feature',
              methodology: 'Scrum',
              teamTechMgr: 'Emily Chen',
              teamPOC: 'John Smith',
              status: 'Active',
              capacity: 8,
            },
            {
              teamId: 302,
              teamName: 'Backend Services',
              type: 'Platform',
              methodology: 'Kanban',
              teamTechMgr: 'Michael Brown',
              teamPOC: 'Jane Doe',
              status: 'Active',
              capacity: 6,
            },
            {
              teamId: 303,
              teamName: 'Data Analytics',
              type: 'Analytics',
              methodology: 'Scrum',
              teamTechMgr: 'Lisa Wang',
              teamPOC: 'Tom Johnson',
              status: 'Active',
              capacity: 5,
            },
            {
              teamId: 304,
              teamName: 'UI/UX Design',
              type: 'Design',
              methodology: 'Design Thinking',
              teamTechMgr: 'Alex Rodriguez',
              teamPOC: 'Sarah Kim',
              status: 'Active',
              capacity: 4,
            },
            {
              teamId: 305,
              teamName: 'DevOps Infrastructure',
              type: 'Infrastructure',
              methodology: 'SRE',
              teamTechMgr: 'Chris Taylor',
              teamPOC: 'Mark Davis',
              status: 'Active',
              capacity: 7,
            },
            {
              teamId: 306,
              teamName: 'Security Team',
              type: 'Security',
              methodology: 'Agile',
              teamTechMgr: 'Rachel Green',
              teamPOC: 'Paul Wilson',
              status: 'Active',
              capacity: 5,
            },
            {
              teamId: 307,
              teamName: 'Quality Assurance',
              type: 'Testing',
              methodology: 'Scrum',
              teamTechMgr: 'Kevin Lee',
              teamPOC: 'Amy Zhang',
              status: 'Active',
              capacity: 6,
            },
            {
              teamId: 308,
              teamName: 'Integration Team',
              type: 'Integration',
              methodology: 'Kanban',
              teamTechMgr: 'Daniel Park',
              teamPOC: 'Sophie Chen',
              status: 'Active',
              capacity: 4,
            },
            {
              teamId: 309,
              teamName: 'Performance Team',
              type: 'Performance',
              methodology: 'Scrum',
              teamTechMgr: 'Jennifer Liu',
              teamPOC: 'Ryan Miller',
              status: 'Active',
              capacity: 5,
            },
            {
              teamId: 310,
              teamName: 'Support Team',
              type: 'Support',
              methodology: 'ITIL',
              teamTechMgr: 'Andrew Kim',
              teamPOC: 'Maria Garcia',
              status: 'Active',
              capacity: 8,
            },
          ],
        },
      },
      {
        portfolioId: 102,
        portfolioName: 'Enterprise Solutions Portfolio',
        portfolioTechMgr: 'Michael Brown',
        pdtCount: 1,
        teamCount: 5,
        productCount: 3,
        pdt: {
          pdtId: 202,
          pdtName: 'Enterprise Integration PDT',
          pdtTechMgr: 'Jennifer Wilson',
          teamCount: 5,
          productCount: 3,
          products: [
            {
              productId: 6,
              productName: 'ERP Integration',
              productOwner: 'Frank Thompson',
              productType: 'Integration',
              status: 'Active',
            },
            {
              productId: 7,
              productName: 'CRM Platform',
              productOwner: 'Grace Lee',
              productType: 'Customer Management',
              status: 'Active',
            },
            {
              productId: 8,
              productName: 'Business Intelligence',
              productOwner: 'Henry Chang',
              productType: 'Analytics',
              status: 'Development',
            },
          ],
          teams: [
            {
              teamId: 401,
              teamName: 'Enterprise API Team',
              type: 'API',
              methodology: 'Scrum',
              teamTechMgr: 'Oliver Smith',
              teamPOC: 'Emma Johnson',
              status: 'Active',
              capacity: 7,
            },
            {
              teamId: 402,
              teamName: 'Database Team',
              type: 'Data',
              methodology: 'Kanban',
              teamTechMgr: 'Sophia Davis',
              teamPOC: 'Lucas Brown',
              status: 'Active',
              capacity: 5,
            },
            {
              teamId: 403,
              teamName: 'Integration Services',
              type: 'Integration',
              methodology: 'Scrum',
              teamTechMgr: 'Isabella Wilson',
              teamPOC: 'Mason Taylor',
              status: 'Active',
              capacity: 6,
            },
            {
              teamId: 404,
              teamName: 'Reporting Team',
              type: 'Analytics',
              methodology: 'Agile',
              teamTechMgr: 'Ethan Anderson',
              teamPOC: 'Ava Martinez',
              status: 'Active',
              capacity: 4,
            },
            {
              teamId: 405,
              teamName: 'Legacy Migration',
              type: 'Migration',
              methodology: 'Waterfall',
              teamTechMgr: 'Noah Garcia',
              teamPOC: 'Mia Rodriguez',
              status: 'Active',
              capacity: 8,
            },
          ],
        },
      },
    ];
  }
}
